### ISSUE TITLE
dialog format?

### ISSUE THREAD

**Issue by dcsan** [narratory/narratory-starter-kit#1]
hi there! This tool and your approach looks really interesting.
It reminds me a bit of the early days of pullstring.io where they had a very "outliner" approach to authoring, which seems a very natural approach for creatives

I saw in your intro page you have a narrative "outline" format...

```
Bot: Hello there, how are you doing?
    User: Oh, it's been a long day.
        Bot: Oh, why is that?
            User: Oh, I have been struggling with flow-chart models for dialog.
                Bot: Oh, yeah. Once it grows beyond a simple prototype, it becomes spaghetti.
```

but then the next set of examples switch to TS / JSON

```js
const question: BotTurn = {
  say: "Have you talked to a bot before?",
  user: [
    { intent: ["Yes", "I have"], bot: "Oh, fun!" },
```

I was wondering if you have some type of parser to convert the two?
or a way to use a less noisy format for authoring such as yaml or markdown (or even emacs org-mode)

**Comment by luddilo** [comment]
Hi! 
Glad to hear that you find the approach interesting! The design philosophy indeed has similarities to Pullstring, and also how we designed social robot apps over at furhatrobotics.com. 

We currently don't have a way to go between the two formats you mention - the former is more used as a way to visualize the design principles. That said, we are working on a simpler authoring tool and I would be happy to discuss your preferences! I'll get back to you on email and close this issue.
